<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-06-17T16:47:42+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.5.1',
    'version_db_installed' => '20190301133300',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1524271792,
        'do_page_reindex_check' => false,
        'latest_version' => '8.4.0',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
];
