<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-23T11:50:49+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.4.0RC2',
    'version_db_installed' => '20180403143200',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1524271792,
        'do_page_reindex_check' => false,
        'latest_version' => '8.3.2',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
];
