<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-21T09:48:43+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'c58 Express Demo',
        ],
    ],
];
