<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-06-17T16:47:22+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      connections.concrete
 * @group     database
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'default-connection' => 'concrete',
    'connections' => [
        'concrete' => [
            'driver' => 'c5_pdo_mysql',
            'server' => '127.0.0.1',
            'database' => 'c5demo_express',
            'username' => 'concrete5',
            'password' => 'concrete5',
            'character_set' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
        ],
    ],
];
